In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import seaborn as sns

In [5]:
sns.__version__ # let's check the version

'0.13.2'

# Orders

In [ ]:
orders_table = pd.read_csv('data/Muesli Project raw data/Orders_Table_1.csv', sep=';')
orders_table.head()
# there is an empty row at the top. the actual index is in the first row

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,D/1/YYYY,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,"90,57",3,0,"11,7741"
2,45,CA-2019-118255,D/3/YYYY,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,"45,98",2,0,"19,7714"
3,48,CA-2019-169194,D/6/YYYY,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,"4,95"
4,60,CA-2019-111682,D/6/YYYY,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,"3,3"

In [29]:
orders_table.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
9990,9894,US-2019-115441,D/7/YYYY,Second Class,SH-19975,Sally Hughsby,Sales,United States,Milwaukee,Wisconsin,53209,Central,Toasted Muesli,With Nuts,FUR-CH-10004626,"403,56",4,0,"96,8544"
9991,9908,US-2018-129007,D/9/YYYY,First Class,KD-16615,Ken Dana,Sales,United States,Anaheim,California,92804,West,Toasted Muesli,With Nuts,FUR-CH-10000155,"717,72",3,"0,2","71,772"
9992,9913,CA-2018-132388,D/10/YYYY,First Class,KN-16390,Katherine Nockton,Sales,United States,Santa Barbara,California,93101,West,Toasted Muesli,With Nuts,FUR-CH-10001714,"362,136",3,"0,2","-54,3204"
9993,9920,CA-2019-149272,D/3/YYYY,Standard Class,MY-18295,Muhammed Yedwab,Sales,United States,Bryan,Texas,77803,Central,Toasted Muesli,With Nuts,FUR-CH-10000863,"528,43",5,"0,3","-143,431"
9994,9948,CA-2020-121559,D/6/YYYY,Second Class,HW-14935,Helen Wasserman,Sales,United States,Indianapolis,Indiana,46203,Central,Toasted Muesli,With Nuts,FUR-CH-10003746,"1925,88",6,0,"539,2464"

In [30]:
orders_table.shape

(9995, 19)

In [ ]:
orders_table.iloc[0]
# column names

Unnamed: 0              Index
Unnamed: 1           Order ID
Unnamed: 2         Order Date
Unnamed: 3          Ship Mode
Unnamed: 4        Customer ID
Unnamed: 5      Customer Name
Unnamed: 6     Origin Channel
Unnamed: 7     Country/Region
Unnamed: 8               City
Unnamed: 9              State
Unnamed: 10       Postal Code
Unnamed: 11            Region
Unnamed: 12          Category
Unnamed: 13      Sub-Category
Unnamed: 14        Product ID
Unnamed: 15             Sales
Unnamed: 16          Quantity
Unnamed: 17          Discount
Unnamed: 18            Profit
Name: 0, dtype: object

In [ ]:
orders_table.info()
# there are no empty values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9995 entries, 0 to 9994
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   9995 non-null   object
 1   Unnamed: 1   9995 non-null   object
 2   Unnamed: 2   9995 non-null   object
 3   Unnamed: 3   9995 non-null   object
 4   Unnamed: 4   9995 non-null   object
 5   Unnamed: 5   9995 non-null   object
 6   Unnamed: 6   9995 non-null   object
 7   Unnamed: 7   9995 non-null   object
 8   Unnamed: 8   9995 non-null   object
 9   Unnamed: 9   9995 non-null   object
 10  Unnamed: 10  9984 non-null   object
 11  Unnamed: 11  9995 non-null   object
 12  Unnamed: 12  9995 non-null   object
 13  Unnamed: 13  9995 non-null   object
 14  Unnamed: 14  9995 non-null   object
 15  Unnamed: 15  9995 non-null   object
 16  Unnamed: 16  9995 non-null   object
 17  Unnamed: 17  9995 non-null   object
 18  Unnamed: 18  9995 non-null   object
dtypes: object(19)
memory usage: 1.4+ MB

In [ ]:
orders_table.duplicated().value_counts()
# there are not duplicates

False    9995
Name: count, dtype: int64

# Campaign Data Table 1

In [ ]:
campaign_data = pd.read_csv('data/Muesli Project raw data/Campaign_Data_Table_1.csv', sep=';')
campaign_data.head()

# file contains 3 empty columns

,Order ID,Arrival Scan Date,Customer Name,Unnamed: 3,Unnamed: 4
328,CA-2020-129707,08/05/2020,Larry Hughes,NaN,NaN
329,CA-2020-125381,08/05/2020,Speros Goranitis,NaN,NaN
330,CA-2020-141733,15/05/2020,Rick Wilson,NaN,NaN
331,US-2020-104451,15/05/2020,Michelle Moray,NaN,NaN
332,US-2020-139647,15/05/2020,Todd Sumrall,NaN,NaN

In [22]:
campaign_data.tail()

,Order ID,Arrival Scan Date,Customer Name,Unnamed: 3,Unnamed: 4
328,CA-2020-129707,08/05/2020,Larry Hughes,NaN,NaN
329,CA-2020-125381,08/05/2020,Speros Goranitis,NaN,NaN
330,CA-2020-141733,15/05/2020,Rick Wilson,NaN,NaN
331,US-2020-104451,15/05/2020,Michelle Moray,NaN,NaN
332,US-2020-139647,15/05/2020,Todd Sumrall,NaN,NaN

In [20]:
campaign_data.shape

(333, 5)

In [19]:
campaign_data.columns

Index(['Order ID', 'Arrival Scan Date', 'Customer Name', 'Unnamed: 3',
       'Unnamed: 4'],
      dtype='object')

In [18]:
campaign_data.info()
# all columns contain string values. Date columns needs to be converted
# No missing values in the first three columns
# Two last columns are completeley empty, need to be removed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           333 non-null    object
 1   Arrival Scan Date  333 non-null    object
 2   Customer Name      333 non-null    object
 3   Unnamed: 3         0 non-null      float64
 4   Unnamed: 4         0 non-null      float64
dtypes: float64(2), object(3)
memory usage: 13.1+ KB

In [ ]:
campaign_data.duplicated().value_counts()
# No duplicates

False    333
Name: count, dtype: int64

# Order Process Data

In [35]:
order_process_data = pd.read_csv('data/Muesli Project raw data/Order_Process_Data_Table_1.csv', sep=';')
order_process_data.head()

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206   D/1/YYYY         07/01/2019              Express
1    4919  CA-2019-160304   D/1/YYYY         09/01/2019  Standard Processing
2    4920  CA-2019-160304   D/1/YYYY         09/01/2019  Standard Processing
3    8604  US-2019-116365   D/1/YYYY         09/01/2019  Standard Processing
4    8605  US-2019-116365   D/1/YYYY         09/01/2019  Standard Processing

In [37]:
order_process_data.tail()

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode
5894,908,CA-2020-143259,D/12/YYYY,06/01/2021,Standard Processing
5895,909,CA-2020-143259,D/12/YYYY,06/01/2021,Standard Processing
5896,1297,CA-2020-115427,D/12/YYYY,06/01/2021,Standard Processing
5897,1298,CA-2020-115427,D/12/YYYY,06/01/2021,Standard Processing
5898,5092,CA-2020-156720,D/12/YYYY,06/01/2021,Standard Processing

In [36]:
order_process_data.shape

(5899, 5)

In [38]:
order_process_data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'On Truck Scan Date', 'Ship Mode'], dtype='object')

In [ ]:
order_process_data.info()
# there are no empty values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5899 entries, 0 to 5898
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              5899 non-null   int64
 1   Order ID            5899 non-null   object
 2   Order Date          5899 non-null   object
 3   On Truck Scan Date  5899 non-null   object
 4   Ship Mode           5899 non-null   object
dtypes: int64(1), object(4)
memory usage: 230.6+ KB

In [ ]:
order_process_data.duplicated().value_counts()
# There are not duplicates

False    5899
Name: count, dtype: int64

# Intern Data Study Table

In [42]:
intern_data_study = pd.read_csv('data/Muesli Project raw data/InternData_Study_Table_1.csv', sep=';')
intern_data_study.head()

         Order ID Ready to Ship Date Pickup Date  Unnamed: 3  Unnamed: 4
0  CA-2019-116540         02/09/2019  03/09/2019         NaN         NaN
1  CA-2019-116540         02/09/2019  03/09/2019         NaN         NaN
2  CA-2019-129847         04/09/2019  04/09/2019         NaN         NaN
3  CA-2019-129630         04/09/2019  04/09/2019         NaN         NaN
4  CA-2019-106278         05/09/2019  06/09/2019         NaN         NaN

In [43]:
intern_data_study.tail()

           Order ID Ready to Ship Date Pickup Date  Unnamed: 3  Unnamed: 4
285  CA-2020-105333         04/12/2020  07/12/2020         NaN         NaN
286  CA-2020-105333         04/12/2020  07/12/2020         NaN         NaN
287  US-2020-110576         04/12/2020  07/12/2020         NaN         NaN
288  CA-2020-119305         04/12/2020  07/12/2020         NaN         NaN
289  CA-2020-142090         07/12/2020  09/12/2020         NaN         NaN

In [ ]:
intern_data_study.shape
# there are 2 empty columns in the dataframe that need to be removed

(290, 5)

In [ ]:
intern_data_study.info()
# there are no empty values
# dates need to be transformed from string into dates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            290 non-null    object
 1   Ready to Ship Date  290 non-null    object
 2   Pickup Date         290 non-null    object
 3   Unnamed: 3          0 non-null      float64
 4   Unnamed: 4          0 non-null      float64
dtypes: float64(2), object(3)
memory usage: 11.5+ KB

In [ ]:
intern_data_study.duplicated().value_counts()
# there are 86 duplicates

False    204
True      86
Name: count, dtype: int64

In [51]:
intern_data_study_duplicates = intern_data_study[intern_data_study.duplicated(keep=False)]
intern_data_study_duplicates.sort_values(by='Order ID')

           Order ID Ready to Ship Date Pickup Date  Unnamed: 3  Unnamed: 4
78   CA-2019-100244         24/09/2019  25/09/2019         NaN         NaN
79   CA-2019-100244         24/09/2019  25/09/2019         NaN         NaN
80   CA-2019-100244         24/09/2019  25/09/2019         NaN         NaN
82   CA-2019-100244         24/09/2019  25/09/2019         NaN         NaN
83   CA-2019-100244         24/09/2019  25/09/2019         NaN         NaN
..              ...                ...         ...         ...         ...
152  US-2020-155425         11/11/2020  12/11/2020         NaN         NaN
225  US-2020-155866         23/11/2020  25/11/2020         NaN         NaN
215  US-2020-155866         23/11/2020  25/11/2020         NaN         NaN
107  US-2020-163790         04/11/2020  06/11/2020         NaN         NaN
104  US-2020-163790         04/11/2020  06/11/2020         NaN         NaN

[147 rows x 5 columns]